

my_app_article_article_add:
    pattern:  /add
    defaults: { _controller: MyAppArticleBundle:article:add }
    
my_app_article_article_show:
    pattern:  /show
    defaults: { _controller: MyAppArticleBundle:article:show }
    
my_app_article_article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppArticleBundle:article:delete }  
       
my_app_article_article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppArticleBundle:article:edit }  