
my_app_article_article_add:
    pattern:  /add
    defaults: { _controller: MyAppArticleBundle:article:add }
    
my_app_article_article_show:
    pattern:  /show
    defaults: { _controller: MyAppArticleBundle:article:show }
    
my_app_article_article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppArticleBundle:article:delete }  
       
my_app_article_article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppArticleBundle:article:edit }  
    
    
my_app_article_article_manage:
    pattern:  /manage
    defaults: { _controller: MyAppArticleBundle:article:manage}
    
my_app_article_article_deletemore:
    pattern:  /deletemore
    defaults: { _controller: MyAppArticleBundle:article:deletemore}