 

 
 
    
my_app_article_style_show:
    pattern:  /show
    defaults: { _controller: MyAppArticleBundle:style:show }

my_app_article_style_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppArticleBundle:style:delete }   
    
my_app_article_style_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppArticleBundle:style:edit }  
 
my_app_article_style_add:
    pattern:  /add
    defaults: { _controller: MyAppArticleBundle:style:add}
my_app_article_style_save:
    pattern:  /save
    defaults: { _controller: MyAppArticleBundle:style:save}