my_app_article_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MyAppArticleBundle:Default:index }

## style ##
my_app_article_style_add:
    pattern:  /style/add
    defaults: { _controller: MyAppArticleBundle:style:add }
my_app_article_style_show:
    pattern:  /style/show
    defaults: { _controller: MyAppArticleBundle:style:show }
    requirements:
        _method:  GET
        id: \d+  
        
## article ##
my_app_article_article_add:
    pattern:  /article/add
    defaults: { _controller: MyAppArticleBundle:article:add }
my_app_article_article_show:
    pattern:  /article/show
    defaults: { _controller: MyAppArticleBundle:article:show }
    requirements:
        _method:  GET
        id: \d+  