

article:
    resource: "@MyAppArticleBundle/Resources/config/routing/article.yml"
    prefix: /{_locale}/article 
    
style:
    resource: "@MyAppArticleBundle/Resources/config/routing/style.yml"
    prefix: /{_locale}/style 
 