

article:
    resource: "@MyAppArticleBundle/Resources/config/routing/article.yml"
    prefix: /article 
    
style:
    resource: "@MyAppArticleBundle/Resources/config/routing/style.yml"
    prefix: /style 
 