parameters:
#    my_app_article.example.class: MyApp\ArticleBundle\Example

services:
#    my_app_article.example:
#        class: %my_app_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
