my_app_article:
    resource: "@MyAppArticleBundle/Resources/config/routing.yml"
    prefix:   /

my_app_forum:
    resource: "@MyAppForumBundle/Resources/config/routing.yml"
    prefix:   /

my_app_user:
    resource: "@MyAppUserBundle/Resources/config/routing.yml"
    prefix:   /

my_app_esprit:
    resource: "@MyAppEspritBundle/Resources/config/routing.yml"
    prefix:   /
## config pour FOSUser  ###
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }


# app/config/routing.yml

_imagine:
    resource: .
    type:     imagine
    
#    
#juanber84_profilercommand:
#    resource: "@Juanber84ProfilercommandBundle/Resources/config/routing.yml"
#    prefix: /

fos_js_routing:
     resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"