security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_EDITOR:      [ROLE_EDITOR, ROLE_USER]     
        ROLE_SUPERSOL:    [ROLE_SUPERSOL, ROLE_EDITOR, ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN ,ROLE_SUPERSOL, ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/publicite, role: ROLE_ADMIN }


# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_EDITOR:      [ROLE_EDITOR, ROLE_USER]     
        ROLE_SUPERSOL:    [ROLE_SUPERSOL, ROLE_EDITOR, ROLE_USER]
        ROLE_ADMIN:       [ROLE_ADMIN ,ROLE_SUPERSOL, ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path:  my_app_esprit_publicite_manage                
               # default_target_path: fos_user_security_login  /*la page a redirect to*/
                remember_me: true          
               # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)#
            remember_me:
                key:         %secret%      
                # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
            logout:
                path:   fos_user_security_logout
                target: /index.php
            anonymous:    true
            
            # logout:       true    par defaut
            #anonymous:    true

   