my_app_forum_homepage:
    pattern:  /api/threads/{id}
    defaults: { _controller: MyAppForumBundle:Default:index }
##############################################################################################    
my_app_forum_tag_add:
    pattern:  /tag/add
    defaults: { _controller: MyAppForumBundle:tag:add }
my_app_forum_tag_show:
    pattern:  /tag/show
    defaults: { _controller: MyAppForumBundle:tag:show }
    requirements:
        _method:  GET
        id: \d+  
my_app_forum_tag_mostusedtag:
    pattern:  /tag/mostusedtag
    defaults: { _controller: MyAppForumBundle:tag:mostused }
    requirements:
        _method:  GET
        id: \d+ 
        ##############################################################################################        
my_app_forum_sujet_add:
    pattern:  /sujet/add
    defaults: { _controller: MyAppForumBundle:sujet:add }
my_app_forum_sujet_show:
    pattern:  /sujet/show
    defaults: { _controller: MyAppForumBundle:sujet:show }
    requirements:
        _method:  GET
        id: \d+  
my_app_forum_sujet_sujetrecent:
    pattern:  /sujet/sujetrecent
    defaults: { _controller: MyAppForumBundle:sujet:sujetrecent }
    requirements:
        _method:  GET
        id: \d+ 
##############################################################################################
my_app_forum_commentaire_add:
    pattern:  /commentaire/add
    defaults: { _controller: MyAppForumBundle:commentaire:add }
my_app_forum_commentaire_show:
    pattern:  /commentaire/show
    defaults: { _controller: MyAppForumBundle:commentaire:show }
    requirements:
        _method:  GET
        id: \d+  


