commentaire:
    resource: "@MyAppForumBundle/Resources/config/routing/commentaire.yml"
    prefix: /{_locale}/commentaire
sujet:
    resource: "@MyAppForumBundle/Resources/config/routing/sujet.yml"
    prefix: /{_locale}/sujet
tag:
    resource: "@MyAppForumBundle/Resources/config/routing/tag.yml"
    prefix: /{_locale}/tag
my_app_forum_homepage:
    pattern:  /api/threads/{id}
    defaults: { _controller: MyAppForumBundle:Default:index }
