my_app_forum_homepage:
    pattern:  /api/threads/{id}
    defaults: { _controller: MyAppForumBundle:Default:index }
    
my_app_forum_tag_add:
    pattern:  /tag/add
    defaults: { _controller: MyAppForumBundle:tag:add }
my_app_forum_tag_show:
    pattern:  /tag/show
    defaults: { _controller: MyAppForumBundle:tag:show }
    requirements:
        _method:  GET
        id: \d+  
