commentaire:
    resource: "@MyAppForumBundle/Resources/config/routing/commentaire.yml"
    prefix: /commentaire
sujet:
    resource: "@MyAppForumBundle/Resources/config/routing/sujet.yml"
    prefix: /sujet
tag:
    resource: "@MyAppForumBundle/Resources/config/routing/tag.yml"
    prefix: /tag
thread:
    resource: "@MyAppForumBundle/Resources/config/routing/thread.yml"
    prefix: /thread