parameters:
#    my_app_forum.example.class: MyApp\ForumBundle\Example

services:
     contenu:
         class: MyApp\ForumBundle\Twig\Extension\ContenuExtension
         tags:
           - {name:twig.extension }
     difftime:
         class: MyApp\ForumBundle\Twig\Extension\DifftimeExtension
         tags:
           - {name:twig.extension }
           ################################################
  