my_app_user_show:
    pattern:  /user/show
    defaults: { _controller: MyAppUserBundle:User:show }
    
my_app_user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: MyAppUserBundle:User:delete}
    
my_app_user_deleteall:
    pattern:  /user/delete
    defaults: { _controller: MyAppUserBundle:User:deleteall}    
    
    
my_app_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: MyAppUserBundle:User:edit}
    
    
my_app_forum_sujet_updateuser:
    pattern:  /updateuser
    defaults: { _controller: MyAppUserBundle:User:updateuser }
 
 
my_app_forum_sujet_updateuser2:
    pattern:  /updateuser2
    defaults: { _controller: MyAppUserBundle:User:updateuser2 }
