my_app_user_show:
    pattern:  /user/show
    defaults: { _controller: MyAppUserBundle:User:show }
    
my_app_user_delete:
    pattern:  /user/{id}/delete
    defaults: { _controller: MyAppUserBundle:User:delete}
    
my_app_user_deleteall:
    pattern:  /user/delete
    defaults: { _controller: MyAppUserBundle:User:deleteall}    
    
    
my_app_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: MyAppUserBundle:User:edit}
    
    
my_app_user_updateuser:
    pattern:  /user/updateuser
    defaults: { _controller: MyAppUserBundle:User:updateuser }
 
 
my_app_user_updateuser2:
    pattern:  /user/updateuser2
    defaults: { _controller: MyAppUserBundle:User:updateuser2 }

 
    
my_app_user_manage:
    pattern:  /user/manage
    defaults: { _controller: MyAppUserBundle:User:manage }  
    
   