 
 
my_app_forum_commentaire_add:
    pattern:  /add
    defaults: { _controller: MyAppForumBundle:commentaire:add }
    
my_app_forum_commentaire_addsouscomment:
    pattern:  /{id}/addsouscomment
    defaults: { _controller: MyAppForumBundle:commentaire:addsouscomment }
    
    
my_app_forum_commentaire_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:commentaire:show }
 
my_app_forum_commentaire_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppForumBundle:commentaire:delete}
    
my_app_forum_commentaire_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppForumBundle:commentaire:edit}
    
my_app_forum_commentaire_editsous:
    pattern:  /{id}/editsous
    defaults: { _controller: MyAppForumBundle:commentaire:editsous}
    
    
    
my_app_forum_commentaire_test:
    pattern:  /test
    defaults: { _controller: MyAppForumBundle:Default:test}