 
 
my_app_forum_commentaire_add:
    pattern:  /add
    defaults: { _controller: MyAppForumBundle:commentaire:add }
    
    
my_app_forum_commentaire_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:commentaire:show }
 

