 
 
my_app_forum_commentaire_add:
    pattern:  /add
    defaults: { _controller: MyAppForumBundle:commentaire:add }
    
my_app_forum_commentaire_addsouscomment:
    pattern:  /addsouscomment
    defaults: { _controller: MyAppForumBundle:commentaire:addsouscomment }
    
    
my_app_forum_commentaire_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:commentaire:show }
 
my_app_forum_commentaire_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppForumBundle:commentaire:delete}