 
 
my_app_forum_commentaire_add:
    pattern:  /add
    defaults: { _controller: MyAppForumBundle:commentaire:add }
    requirements:
        _method:  POST|GET
    options:
        expose: true
        
my_app_forum_commentaire_addsouscomment:
    pattern:  /{id}/addsouscomment
    defaults: { _controller: MyAppForumBundle:commentaire:addsouscomment }
    requirements:
        _method:  POST|GET
    options:
        expose: true
    
my_app_forum_commentaire_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:commentaire:show }
 
my_app_forum_commentaire_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppForumBundle:commentaire:delete}
    
my_app_forum_commentaire_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppForumBundle:commentaire:edit}
    requirements:
        _method:  POST|GET
    options:
        expose: true
        

my_app_forum_commentaire_vote:
    pattern:  /{id}/vote
    defaults: { _controller: MyAppForumBundle:commentaire:vote}
    requirements:
        _method:  POST|GET
    options:
        expose: true   
        
my_app_forum_commentaire_novote:
    pattern:  /{id}/novote
    defaults: { _controller: MyAppForumBundle:commentaire:novote}
    requirements:
        _method:  POST|GET
    options:
        expose: true       
       
       
my_app_forum_commentaire_editsouscomment:
    pattern:  /{id}/editsouscomment
    defaults: { _controller: MyAppForumBundle:commentaire:editsouscomment}
    requirements:
        _method:  POST|GET
    options:
        expose: true
 