my_app_forum_sujet_add:
    pattern:  /add
    defaults: { _controller: MyAppForumBundle:sujet:add }
my_app_forum_sujet_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:sujet:show }
    requirements:
        _method:  GET
        id: \d+  
my_app_forum_sujet_sujetrecent:
    pattern:  /sujetrecent 
    defaults: { _controller: MyAppForumBundle:sujet:sujetrecent }
    requirements:
        _method:  GET
        id: \d+ 
my_app_forum_sujet_manage:
    pattern:  /manage
    defaults: { _controller: MyAppForumBundle:sujet:manage }
    requirements:
        _method:  GET
        id: \d+   
        
my_app_forum_sujet_mostreadsujet:
    pattern:  /mostreadsujet
    defaults: { _controller: MyAppForumBundle:sujet:mostreadsujet }
    
    
my_app_forum_sujet_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppForumBundle:sujet:delete}
    
my_app_forum_sujet_deleteall:
    pattern:  /delete/all
    defaults: { _controller: MyAppForumBundle:sujet:deleteall}
    
my_app_forum_sujet_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppForumBundle:sujet:edit}
    
    
my_app_forum_sujet_voir:
    pattern:  /{id}/voir
    defaults: { _controller: MyAppForumBundle:sujet:voir }
    
my_app_forum_sujet_selectsujet:
    pattern:  /selectsujet
    defaults: { _controller: MyAppForumBundle:sujet:selectsujet }
 
 
my_app_forum_sujet_selectsujet2:
    pattern:  /selectsujet2
    defaults: { _controller: MyAppForumBundle:sujet:selectsujet }