 
     
my_app_forum_tag_manage:
    pattern:  /manage
    defaults: { _controller: MyAppForumBundle:tag:manage }
my_app_forum_tag_show:
    pattern:  /show
    defaults: { _controller: MyAppForumBundle:tag:show }
   
my_app_forum_tag_mostusedtag:
    pattern:  /mostusedtag
    defaults: { _controller: MyAppForumBundle:tag:mostused }
   
        
my_app_forum_tag_usedtag:
    pattern:  /usedtag
    defaults: { _controller: MyAppForumBundle:tag:usedtag}
    
        
        
my_app_forum_tag_delete:
    pattern:  /delete
    defaults: { _controller: MyAppForumBundle:tag:delete}
    
my_app_forum_tag_deleteall:
    pattern:  /delete/all
    defaults: { _controller: MyAppForumBundle:tag:deleteall}
    
my_app_forum_tag_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppForumBundle:tag:edit}  
 