my_app_esprit_menu_add:
    pattern:  /add
    defaults: { _controller: MyAppEspritBundle:menu:add }
my_app_esprit_menu_show:
    pattern:  /show
    defaults: { _controller: MyAppEspritBundle:menu:show } 
 
my_app_esprit_menu_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppEspritBundle:menu:edit}  
    
my_app_esprit_menu_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppEspritBundle:menu:delete}  