my_app_esprit_menu_add:
    pattern:  /add
    defaults: { _controller: MyAppEspritBundle:menu:add }
my_app_esprit_menu_show:
    pattern:  /show
    defaults: { _controller: MyAppEspritBundle:menu:show } 
 
my_app_esprit_menu_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppEspritBundle:menu:edit}  
    
my_app_esprit_menu_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppEspritBundle:menu:delete}  
    
my_app_esprit_menu_list:
    pattern:  /list
    defaults: { _controller: MyAppEspritBundle:menu:list}  
    
my_app_esprit_menu_recherche:
    pattern:  /recherche
    defaults: { _controller: MyAppEspritBundle:menu:recherche}
    
my_app_esprit_menu_search:
    pattern:  /search
    defaults: { _controller: MyAppEspritBundle:menu:search}
 
    
    