my_app_esprit_notif_show:
    pattern:  /testnotif
    defaults: { _controller: MyAppEspritBundle:notification:testnotif } 
    
    
my_app_esprit_notif_shownumber:
    pattern:  /shownumber
    defaults: { _controller: MyAppEspritBundle:notification:shownumber } 