my_app_esprit_publicite_add:
    pattern:  /add
    defaults: { _controller: MyAppEspritBundle:publicite:add }
my_app_esprit_publicite_show:
    pattern:  /show
    defaults: { _controller: MyAppEspritBundle:publicite:show }
    requirements:
        _method:  GET
        id: \d+  
my_app_esprit_publicite_manage:
    pattern:  /manage
    defaults: { _controller: MyAppEspritBundle:publicite:manage }
    requirements:
        _method:  GET
        id: \d+  
my_app_esprit_publicite_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyAppEspritBundle:publicite:delete}
    
my_app_esprit_publicite_deleteall:
    pattern:  /delete/all
    defaults: { _controller: MyAppEspritBundle:publicite:deleteall}
    
my_app_esprit_publicite_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyAppEspritBundle:publicite:edit}  
    
my_app_esprit_publicite_deletemore:
    pattern:  /deletemore
    defaults: { _controller: MyAppEspritBundle:publicite:deletemore}