my_app_esprit_homepage:
    pattern:  /index.php
    defaults: { _controller: MyAppArticleBundle:article:show }
    
 
    
my_app_esprit_administration:
    pattern:  /administration
    defaults: { _controller: MyAppEspritBundle:Default:administration }    
    
publicite:
    resource: "@MyAppEspritBundle/Resources/config/routing/publicite.yml"
    prefix: /publicite 
    
    
   
menu:
    resource: "@MyAppEspritBundle/Resources/config/routing/menu.yml"
    prefix: /menu 


 