my_app_esprit_homepage:
    pattern:  /index.php
    defaults: { _controller: MyAppArticleBundle:article:show }
    
    
my_app_esprit_route:
    pattern:  /route
    defaults: { _controller: MyAppEspritBundle:Default:route }
 
    
    
my_app_esprit_administration:
    pattern:  /administration
    defaults: { _controller: MyAppEspritBundle:Default:administration } 
   
    
publicite:
    resource: "@MyAppEspritBundle/Resources/config/routing/publicite.yml"
    prefix: /publicite 
    
notif:
    resource: "@MyAppEspritBundle/Resources/config/routing/notification.yml"
    prefix: /notif     
   
menu:
    resource: "@MyAppEspritBundle/Resources/config/routing/menu.yml"
    prefix: /menu 

 

 