my_app_esprit_homepage:
    pattern:  /index.php
    defaults: { _controller: MyAppArticleBundle:article:show }
  
my_app_esprit_route:
    pattern:  /route
    defaults: { _controller: MyAppEspritBundle:Default:route }
 
  
my_app_esprit_administration:
    pattern:  /administration
    defaults: { _controller: MyAppEspritBundle:Default:administration } 
   
    
publicite:
    resource: "@MyAppEspritBundle/Resources/config/routing/publicite.yml"
    prefix: /publicite 
    
notif:
    resource: "@MyAppEspritBundle/Resources/config/routing/notification.yml"
    prefix: /notif     
   
menu:
    resource: "@MyAppEspritBundle/Resources/config/routing/menu.yml"
    prefix: /menu 

signe:
    resource: "@MyAppEspritBundle/Resources/config/routing/signe.yml"
    prefix: /signe 
     
 
my_app_esprit_test:
    pattern:  /test
    defaults: { _controller: MyAppEspritBundle:Default:test }
    
 
my_app_esprit_translation:
    pattern:  /translation
    defaults: { _controller: MyAppEspritBundle:Default:translation }
 