my_app_esprit_homepage:
    pattern:  /index.php
    defaults: { _controller: MyAppArticleBundle:article:show }
  
my_app_esprit_route:
    pattern:  /{_locale}/route
    defaults: { _controller: MyAppEspritBundle:Default:route }
 
  
my_app_esprit_administration:
    pattern:  /{_locale}/administration
    defaults: { _controller: MyAppEspritBundle:Default:administration } 
   
    
publicite:
    resource: "@MyAppEspritBundle/Resources/config/routing/publicite.yml"
    prefix: /{_locale}/publicite 
    
notif:
    resource: "@MyAppEspritBundle/Resources/config/routing/notification.yml"
    prefix: /{_locale}/notif     
   
menu:
    resource: "@MyAppEspritBundle/Resources/config/routing/menu.yml"
    prefix: /{_locale}/menu 

signe:
    resource: "@MyAppEspritBundle/Resources/config/routing/signe.yml"
    prefix: /{_locale}/signe 
     
 
my_app_esprit_test:
    pattern:  /test
    defaults: { _controller: MyAppEspritBundle:Default:test }
 
    
    
 
my_app_esprit_translation:
    pattern:  /{_locale}/translation
    defaults: { _controller: MyAppEspritBundle:Default:translation }
    requirements:
        _locale: en|fr
    
myapp_acteur_rechercher:
  pattern: /lister
  defaults: { _controller: MyAppEspritBundle:Default:lister }
  
  
  
rn_phototekbundle_ajax:
  pattern: /newFormAjax
  defaults: { _controller: MyAppEspritBundle:Default:newFormAjax }
 