parameters:
#    my_app_esprit.example.class: MyApp\EspritBundle\Example

services:
#    my_app_esprit.example:
#        class: %my_app_esprit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]



# KnpMenuBundle
services:
    myapp_esprit.menu.menu_builder:
        class: MyApp\EspritBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    myapp_main.menu.main:
        class: KnpMenuMenuItem
        factory_service: myapp_esprit.menu.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main } # L'alias est très important, c'est avec lui que vous appellerez votre menu dans la vue